bunadmin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]

dashboard/urls.py
from django.urls import path
from .views import IndexDashboardTemplateView, SetLanguageView

app_name='dashboard' 

urlpatterns = [
    path('', IndexDashboardTemplateView.as_view(), name='index'),
    path('set_language', SetLanguageView.as_view(), name='set_language'),
]

users/urls.py
from django.urls import path
from .views import LoginPageView
from django.contrib.auth.views import LogoutView

app_name='users' 

urlpatterns = [
    path('', LoginPageView.as_view() , name='login'),
    # path('register', RegistrationView.as_view() , name='register'),
    # path('logout', LogoutView.as_view(), name='logout'),
]

dashboard/models.py
from django.db import models

# Create your models here.
class Country(models.Model):
    name = models.CharField(max_length=20, unique=True, db_index=True)
    flag = models.ImageField(upload_to='flags/')
    code = models.CharField(max_length=10,unique=True)

class Language(models.Model):
    name = models.CharField(max_length=20, unique=True, db_index=True)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, related_name='languages')

products/models.py
from django.db import models

# Create your models here.

users/models.py
from typing import Iterable
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.forms import ValidationError
from django.utils.text import slugify






class User(AbstractBaseUser):
    first_name = models.CharField(max_length=30,db_index=True)
    last_name  = models.CharField(max_length=30, db_index=True)
    email = models.EmailField(unique=True, db_index=True)
    is_active = models.BooleanField(default=False)
    slug = models.SlugField(null=True, blank=True, unique=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)


    USERNAME_FIELD  = 'email'
    REQUIRED_FIELDS = []

    def save(self, *args, **kwargs):
        if not self.slug:
           slug_value = f"{self.first_name}-{self.last_name}"
           self.slug = slugify(slug_value)
        super().save(*args, **kwargs)

class Profile(models.Model):
    user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='profile')
    phone_number = models.CharField(max_length=15, unique=True)
    is_phone_set = models.BooleanField(default=False)
    is_email_verified = models.BooleanField(default=False)
    is_mfa_enable = models.BooleanField(default=False)
    image = models.ImageField(upload_to='users')

class Address(models.Model):
    user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='addresses')
    street_address = models.CharField(max_length=255)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    postal_code = models.CharField(max_length=20)
    country = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, null=True, blank=True)
    is_primary = models.BooleanField(default=False)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['is_primary'],
                condition=models.Q(is_primary=True),
                name='unique_primary_address_per_user'
            )
        ]

    def __str__(self):
        return f'{self.street_address}, {self.city}, {self.state}, {self.country} - {self.postal_code}'

    def clean(self):
        if self.is_primary:
            primary_address = Address.objects.filter(user=self.user, is_primary=True).exclude(id=self.id)
            if primary_address.exists():
                raise ValidationError('There can be only one primary address per profile.')

    def save(self, *args, **kwargs):
        self.clean()
        if not self.slug:
            self.slug = slugify(self.street_address)
        super().save(*args, **kwargs)
       

    
    
       



    

users/forms.py
from typing import Any
from django import forms
from .models import User
from django.core.mail import send_mail

class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'password')

    

dashboard/views.py
from django.views.generic import TemplateView, View
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import translation
from bunadmin.settings import LANGUAGES_CODES




class IndexDashboardTemplateView(TemplateView):
    template_name = 'dashboard/index.html'

    def get_context_data(self,*args ,**kwargs):
        context = super().get_context_data(**kwargs)
        return context


class SetLanguageView(View):
    http_method_names = ['post']

    def post(self, request, language = 'fr', next_to=reverse('dashboard:index')):
        if language not in LANGUAGES_CODES:
           set_language(request=request)
           return HttpResponseRedirect(redirect_to=next_to)
        
        set_language(request, language)
        return HttpResponseRedirect(redirect_to=next_to)
            
            

def set_language(request, language='fr'):
    translation.activate(language=language)
    request.session['django_language'] = language

products/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate , login
from django.http import HttpResponseRedirect
from django.views.generic import View
from .forms import LoginForm
from .models import User

class LoginPageView(View):

    def get(self,request):
        form = LoginForm()
        context = {'form': form}
        return render(request=request,template_name='users/login.html', context=context)

    def post(self,request):
        form = LoginForm(request.POST)
        context = {'form': form}
        if form.is_valid():
            email = form.clean('email')
            password = form.clean('password')
            user = authenticate(request, email, password)
            if not user:
                form.add_error('Error invalid email or password!')
                return render(request,'users/login.html', context)
            login(request, user)
            dashboard_url = reversed('dashboard:home')
            return HttpResponseRedirect(redirect_to=dashboard_url)
        return render(request=request,template_name='users/login.html', context=context)

    

templates/base-nonav.html
{% load static %}
<!DOCTYPE html>
<html :class="{ 'theme-dark': dark }" x-data="data()" lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/png" href="{%  static 'imgs/favicon.png' %}"/>
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static '/css/dist/output.css' %}" />
    <script type="module" src="{% static '/js/libs/stimulus.umd.min.js'  %}"></script>
    <script type="module" src="{% static '/js/dist/application.js'  %}"></script>
  </head>
  <body>
    {% block content %} {% endblock %}
  </body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <meta
      name="viewport"
      content="user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, width=device-width"
    />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    {% include './partials/navbar.html' %}
    {% include './partials/sidebar.html' %}
    {% block content %}{% endblock %}
    {% include './partials/footer.html' %}
  </body>
</html>

templates/partials/footer.html
<div class="flex flex-row items-centers justified-between">
  <p class="text-base font-medium px-2 py-2">
    Made with Love by <span class="font-bold">Abdiwali Maxamed</span>
  </p>
  <p class="font-light text-base px-2 py-2">@copyright Afronectar PL 2024</p>
</div>

users/templates/users/login.html
{% extends 'base-nonav.html' %} 
{% load static %} 
{% load i18n %}
{% block title %}Login - BUNADMIN Dashboard {% endblock %} 
{% block content %}
<div class="flex items-center min-h-screen p-6 bg-gray-50 dark:bg-gray-900">
  <div
    class="flex-1 h-full max-w-4xl mx-auto overflow-hidden bg-white rounded-lg shadow-xl dark:bg-gray-800"
  >
    <div class="flex flex-col overflow-y-auto md:flex-row">
      <div class="h-32 relative md:h-auto md:w-1/2">
        <img
          aria-hidden="true"
          class="object-cover w-56 absolute max-h-auto m-auto top-0 bottom-0 left-0 right-0 "
          src="{% static '/svgs/logo.svg' %}"
          alt="Office"
          />
        <img
          aria-hidden="true"
          class="object-cover w-full h-full dark:hidden"
          src="{% static '/imgs/office-work-coffee.jpg' %}"
          alt="Office"
        />
      </div>
      <div class="flex items-center justify-center p-6 sm:p-12 md:w-1/2">
        <div class="w-full">
          <form  data-controller="set_language" method="post" action="{% url 'dashboard:set_language' %}">
                {% csrf_token %}
                <select data-action="change->set_language#submitForm" title="language" name="language" class="select select-ghost select-xs font-normal text-gray-600 capitalized focus:outline-none mb-4">
                  {% for language in languages %}
                    <option class="font-normal" value="{{language}}">
                      {{language}}
                    </option>
                  {% endfor %}
                </select>
          </form>
          <h1
            class="mb-4 text-2xl font-semibold text-center text-gray-700 dark:text-gray-200"
          >
           {% trans 'Welcome to Afronectar Administration Portal' %}
          </h1>

          <h2
            class="mb-4 text-xl font-semibold text-gray-700 dark:text-gray-200"
          >
            {% trans 'Login' %}
          </h2>
          <form method="post" action="{% url 'users:login' %}">
            <label class="block text-sm">
              <span class="text-gray-700 dark:text-gray-400">{% trans 'Email' %}</span>
              <input
                class="block w-full mt-1 text-sm border border-1 border-gray-300 h-10 px-2 rounded-lg dark:border-gray-600 dark:bg-gray-700 focus:border-green-400 focus:outline-none focus:shadow-outline-green dark:text-gray-300 dark:focus:shadow-outline-gray"
                type="email"
                required
                placeholder="name@afronectar.ch"
              />
            </label>
            <label class="block mt-4 text-sm">
              <span class="text-gray-700 dark:text-gray-400">{% trans 'Password' %}</span>
              <input
                class="block w-full mt-1 text-sm border border-1 border-gray-300 h-10 px-2 rounded-lg dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input"
                placeholder="***************"
                type="password"
              />
            </label>
  
            <button
              class="block w-full px-4 py-2 mt-4 text-sm font-medium leading-5 text-center text-white transition-colors duration-150 bg-green-600 border border-transparent rounded-lg active:bg-green-600 hover:bg-green-700 focus:outline-none focus:shadow-outline-purple"
              type='submit'
            >
              {% trans 'Log in' %}
            </button>
          </form>

          <hr class="my-8" />

          <a
             href='#'
            class="flex items-center justify-center gap-2 w-full px-4 py-2 text-sm font-medium leading-5  text-gray-700 transition-colors duration-150 border border-gray-300 rounded-lg dark:text-gray-400 active:bg-transparent hover:border-gray-500 focus:border-gray-500 active:text-gray-500 focus:outline-none focus:shadow-outline-gray"
          >
          <svg class="fill-green-600 w-6 h-auto" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 488 512"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M488 261.8C488 403.3 391.1 504 248 504 110.8 504 0 393.2 0 256S110.8 8 248 8c66.8 0 123 24.5 166.3 64.9l-67.5 64.9C258.5 52.6 94.3 116.6 94.3 256c0 86.5 69.1 156.6 153.7 156.6 98.2 0 135-70.4 140.8-106.9H248v-85.3h236.1c2.3 12.7 3.9 24.9 3.9 41.4z"/></svg>
            Google
          </a>
          <a
            href='#'
            class="flex items-center justify-center w-full px-4 py-2 mt-4 text-sm font-medium leading-5 gap-2 text-gray-700 transition-colors duration-150 border border-gray-300 rounded-lg dark:text-gray-400 active:bg-transparent hover:border-gray-500 focus:border-gray-500 active:text-gray-500 focus:outline-none focus:shadow-outline-gray"
          >
            <svg class="fill-green-600 w-5 h-auto" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M80 299.3V512H196V299.3h86.5l18-97.8H196V166.9c0-51.7 20.3-71.5 72.7-71.5c16.3 0 29.4 .4 37 1.2V7.9C291.4 4 256.4 0 236.2 0C129.3 0 80 50.5 80 159.4v42.1H14v97.8H80z"/></svg>
            Facebook
          </a>

          <p class="mt-4">
            <a
              class="text-sm font-medium text-green-600 dark:text-purple-400 hover:underline"
              href="./forgot-password.html"
            >
              {% trans 'Forgot your password?' %}
            </a>
          </p>
          <p class="mt-1">
            <a
              class="text-sm font-medium text-green-600 dark:text-purple-400 hover:underline"
              href="./create-account.html"
            >
              {% trans 'Create account' %}
            </a>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}